### ISSUE TITLE
cncli do not work with "EnableP2P": true on 1.35.0-rc2

### ISSUE THREAD

**Issue by os11k** [cardano-community/cncli#1]
**Describe the bug**
When I try to run CNLI 4.0.4 on 1.35.0-rc2 with enabled p2p(`"EnableP2P": true` in config.json and corresponding topology.json), I got following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/cardano_ouroboros_network-0.2.8/src/mux/connection.rs:202:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
run cncli 4.0.4:

`cncli sync --host 127.0.0.1 --port 6003 --no-service --network-magic 1097911063`

**Expected behavior**
CNCLI should work

- OS: official cardano-node docker image - 1.35.0-rc2 tag

I would like to add that CNCLI works as expected on 1.35.0-rc2 when p2p is not enabled.

**Comment by rdlrt** [comment]
While you can report cncli issues [here](https://github.com/cardano-community/cncli) , the guild tools will not be rushing into supporting beta versions while known issues/changes are pending upstream. There was a warn set out for the tools beforehand on the [announcements channel](https://t.me/c/1363966908/3133) regarding the same.

**Comment by os11k** [comment]
Hi @rdlrt ! I can't see that announcement in that TG channel. Could you please invite me there?

Additionally @AndrewWestberg specifically pointed to me that this repo is one what should be used.

![image](https://user-images.githubusercontent.com/6322576/173234033-358752cd-89db-447e-9c16-8a38b003a0ca.png)

**Comment by rdlrt** [comment]
> Hi @rdlrt ! I can't see that announcement in that TG channel. Could you please invite me there?
> 
> Additionally @AndrewWestberg specifically pointed to me that this repo is one what should be used.
> 
> ![image](https://user-images.githubusercontent.com/6322576/173234033-358752cd-89db-447e-9c16-8a38b003a0ca.png)
>  

It is a public group, available to all to join - direct link [here](https://t.me/guild_operators_official/44)

**Comment by rdlrt** [comment]
> Hi @rdlrt ! I can't see that announcement in that TG channel. Could you please invite me there?
> 
> Additionally @AndrewWestberg specifically pointed to me that this repo is one what should be used.
> 
> ![image](https://user-images.githubusercontent.com/6322576/173234033-358752cd-89db-447e-9c16-8a38b003a0ca.png)

My bad, I misread the notification title thinking it's reported against guild-operators repo, You're right to raise it here

**Comment by AndrewWestberg** [comment]
I will be taking a look at supporting the new node version next week. Thanks for reporting

**Comment by AndrewWestberg** [comment]
@os11k Has this issue been resolved?

**Comment by os11k** [comment]
Hi @AndrewWestberg ! Thank you, that bug has been fixed for a while already.
