### ISSUE TITLE
send protocol versions to pooltool for all blocks

### ISSUE THREAD

**Issue by papacarp** [cardano-community/cncli#11]
**Is your feature request related to a problem? Please describe.**
db-sync can gather protocol versions from block headers, but for pooltool we collect all orphan blocks and won't have access to the protocol version.

**Describe the solution you'd like**
To have the ability record protocol versions from block headers even for orphan blocks we'd like cncli to pass that info as part of the sendtips package

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by AndrewWestberg** [comment]
Resolved in 5.0.5
