### ISSUE TITLE
Minted a block despite empty leader logs

### ISSUE THREAD

**Issue by lunarpool** [cardano-community/cncli#13]
Hi Andrew,

this is the first time I see something like that so decided to report. I did not check whether this is some kind of known issue or already reported.

My pool MOON1 minted a block despite having empty leader logs for that epoch, I tried to generate it on different machines using different versions, but same result all the time.

Ticker: MOON1
Epoch: 353
Block height: 7558849

Leader logs machine setup:
CNCLI version: 5.0.6, 5.0.5, 5.0.4 (tested all three)
Cardano-node version: 1.35.2

Leader logs machine 2 setup:
CNCLI version: 5.0.6, 5.0.4 (tested both)
Cardano-node version: 1.34.1

Leader logs were empy using any combination of the above cardano-node and cncli version:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/58665645/181771929-57574d2b-ee65-4de5-843c-6016ffb4a60c.png">

Block created:

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/58665645/181772357-6536db15-a77c-4c87-8e3a-d9829691c3c5.png">

I hope I have provided all necessary information. Feel free to contact me if more detail is needed.
Thank you

Dusan
lunarpool.io

**Comment by AndrewWestberg** [comment]
@lunarpool Can you re-run with 5.0.6 and add in the debug flag to capture more logs? Can you also give me the exact command-line params you ran with?  Did you run with `--consensus tpraos`?

```
RUST_LOG=debug cncli leaderlog...
```

**Comment by lunarpool** [comment]
Hi @AndrewWestberg,

There is no `--consensus` parameter set, but it seems to do the trick, so I probably just missed the need to use it.

Debug log without `--consensus`:

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/58665645/181798198-44d1ec4a-0bc9-4986-99cb-05d3c1fff3e2.png">

Using `--consensus tpraos`:

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/58665645/181800968-33cb1b84-c30e-451f-9179-248fb1fdd648.png">

**Comment by lunarpool** [comment]
Just reading v5.0.0 release notes, it is obvious this is my bad.

Sorry for disturbing
Dusan

**Comment by AndrewWestberg** [comment]
@lunarpool No worries. I was obviously planning to already be in the Babbage era at this point, so the defaults in the 5.x releases were set with Babbage assumptions. Since Alonzo has gotten extended, the tpraos consensus is required.
