### ISSUE TITLE
CNCLI memory usage

### ISSUE THREAD

**Issue by ChangePool** [cardano-community/cncli#15]
Please publish and maintain accurate memory usage requirements for running the CNCLI binary on a computer also running Cardano Node in one of various roles, including as a relay or block producer.

**Comment by AndrewWestberg** [comment]
The memory usage for using cncli are miniscule. The problem is `cardano-cli query stake-snapshot`. I can't control this and the memory it takes depends on how many staked wallets there are.

**Comment by ChangePool** [comment]
When calculating slot leadership, how much memory may `cardano-cli query stake-snapshot` currently require with few staked wallets? An average number of staked wallets? A large number?

If other factors are also involved in the memory requirements for calculating slot leadership, which seems likely, how may the requirements be growing over time?

**Comment by AndrewWestberg** [comment]
I don't know. That's on IOG to document as they created cardano-cli. I don't support that tool here.
