### ISSUE TITLE
laderlog calculation requires localdb

### ISSUE THREAD

**Issue by nemo83** [cardano-community/cncli#18]
**Is your feature request related to a problem? Please describe.**
The cncli leaderlog command requires local db, I guess, to extract the epoch nonce. I'm planning to use cncli just for the leaderlogs calculation and not connected to any node, hence I can't build the db.

**Describe the solution you'd like**
It would be nice if the nonce could be an optional input paramter of lederlog calculation, instead of having an hard dependecy on the local db. should the nonce not being input, cncli should fallback on local db

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sunapi386** [comment]
Good idea. But it would be nice if you can explain where cncli would query for the epoch nonce. Do you have any thoughts?

Two thoughts here: 
1. I think it may be possible to replace cncli's db with that of cardano-db-sync's use of postgres, if that was already available. 
2. It's possible to query directly to cardano-node locally using cardano-cli. E.g.
```
cardano-cli query leadership-schedule \
--mainnet \
--genesis $CNODE_HOME/shelley-genesis.json \
--stake-pool-id (cat $CNODE_HOME/stakepoolid.txt) \
--vrf-signing-key-file $CNODE_HOME/vrf.skey \
--next
```

Any particular reason you can't build the db by connecting to a node?

**Comment by AndrewWestberg** [comment]
@nemo83 v6.0.0-alpha5 has an option to pass a `--nonce` value to leaderlogs. It does not require a populated local db.
