### ISSUE TITLE
`cardano-cli query leadership-schedule` not match with `cncli leaderlog`

### ISSUE THREAD

**Issue by eric248550** [cardano-community/cncli#20]
**Internal/External**
*External* 

**Summary**
`cardano-cli query leadership-schedule` not match with `cncli leaderlog`

**Steps to reproduce**
`cardano-cli query leadership-schedule` not match with `cncli leaderlog`

**Expected behavior**
cncli should match with leader-schedule

**Screenshots and attachments**
Run `cardano-cli query leadership-schedule`
`cardano-cli query leadership-schedule --mainnet --genesis mainnet-shelley-genesis.json --stake-pool-id a59e2c8422ed40242742f3b6e8219fa0c454eaa7288d71981d3b65a9 --vrf-signing-key-file vrf.skey --current`
**Output**:
```
     SlotNo                          UTC Time              
-------------------------------------------------------------
     75451711                   2022-10-29 04:33:22 UTC
```

Run `cncli leaderlog`
```
{
  "status": "ok",
  "epoch": 372,
  "epochNonce": "b584ff31eb230b45c48c6f989751f2a574cfd96b9f6431e26263daf38bc4f416",
  "consensus": "tpraos",
  "epochSlots": 0,
  "epochSlotsIdeal": 0.47,
  "maxPerformance": 0.0,
  "poolId": "a59e2c8422ed40242742f3b6e8219fa0c454eaa7288d71981d3b65a9",
  "sigma": 0.00002193411086384421,
  "activeStake": 550266011819,
  "totalActiveStake": 25087226705234193,
  "d": 0.0,
  "f": 0.05,
  "assignedSlots": []
}
```

**Comment by AndrewWestberg** [comment]
You need to run cncli with `--consensus praos`
