### ISSUE TITLE
cncli leader log calculations using significant memory

### ISSUE THREAD

**Issue by adavault-ops** [cardano-community/cncli#23]
**Describe the bug**
cncli leader log calculations crashing cardano-node due to excessive memory use. Peak memory use for the node and cmcli is now 26.5GB from Epoch 282

**To Reproduce**
1. Install cncli (via GuildOps tools in our case)
2. Pass the point in the epoch where leaderlogs calculations start
3. Wait for the leaderlogs calculations to conclude- memory use will peak as the results are written to database?

**Expected behavior**
It should be possible to run cardano-node and cncli in less than 20GB

**Screenshots**

**Server (please complete the following information):**
 - OS: ubuntu 20.04 server LTS
 - Browser n/a
 - Version 5.2.0

**Additional context**
Physical memory on the servers is set to 20GB, by increasing swap it works correctly and does not crash the node. However passing beyond physical memory makes it possible that the node may be delayed if assigned leader slots coincide.

**Comment by AndrewWestberg** [comment]
Not a cncli issue: https://github.com/input-output-hk/cardano-node/issues/3691

**Comment by adavault-ops** [comment]
Thanks for the quick response
