### ISSUE TITLE
Can't run cncli v5.3.0 on debian 11 bullseye 

### ISSUE THREAD

**Issue by os11k** [cardano-community/cncli#26]
**Describe the bug**
when I run `cncli --version` on debian 11, I get:

```
./cncli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./cncli)
./cncli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./cncli)
./cncli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./cncli)
```
**To Reproduce**
run `cncli --version` on debian 11

**Expected behavior**
cncli works

**Desktop (please complete the following information):**
 - OS: Debian 11 bullseye 

I will try to build glibc from sources, but it is not really what I want to do :(

**Comment by AndrewWestberg** [comment]
For Debian, you're going to need to build it from scratch.
