### ISSUE TITLE
can't build v5.3.1 on previously reliable platform

### ISSUE THREAD

**Issue by rphair** [cardano-community/cncli#28]
**Describe the bug**
When compiling as per instructions for `v5.3.0` and every version we successfully built before that, the build fails with the following error:
```
$ git checkout v5.3.1
$ cargo install --path . --force
  Installing cncli v5.3.1 (/home/spo/src/cncli)
    Updating crates.io index
error: failed to compile `cncli v5.3.1 (/home/spo/src/cncli)`, intermediate artifacts can be found at `/home/spo/src/cncli/target`
Caused by:
  cannot produce proc-macro for `ctor v0.1.26` as the target `x86_64-unknown-linux-gnu` does not support these crate types
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - `cargo 1.67.1 (8ecd4f20a 2023-01-10)`

**Additional context**
Both the [release notes for this version](https://github.com/cardano-community/cncli/releases/tag/v5.3.1) and this Rust issue (https://github.com/rust-lang/rust/issues/78210) mention `+crt-static`.  The release notes don't currently say why this option is mentioned...  maybe it's a compiler option that needs to be added to the build process (or taken away from it)?  Note except for building `cardano-node` I am a Rust n00b.

**Comment by AndrewWestberg** [comment]
See the new build instructions:

```
cargo install --path . --force --target x86_64-unknown-linux-gnu
```
