### ISSUE TITLE
Leaderlog did not return full results

### ISSUE THREAD

**Issue by mccamca** [cardano-community/cncli#32]
Running leaderlog-current in epoch 408 did not return full list of expected blocks. Cardano-cli tool shows 5 blocks, cncli shows 2 blocks. This morning I produced one of the expected blocks indicated by cardano-cli that was not included in the cncli report. No issues with leaderlog checks prior to epoch 408 (I typically run 'next' rather than 'current').

export SNAPSHOT=$(cardano-cli query stake-snapshot --stake-pool-id <pool-id> --mainnet)
export POOL_STAKE=$(echo $SNAPSHOT | jq .poolStakeMark)
export ACTIVE_STAKE=$(echo $SNAPSHOT | jq .activeStakeMark)
nice -n 19 cncli leaderlog --pool-id <pool_id> --pool-vrf-skey <path-to-vrf-skey> --byron-genesis <path-to-byron-genesis> --shelley-genesis <path-to-shelly-genesis> --pool-stake $POOL_STAKE --active-stake $ACTIVE_STAKE --consensus praos --ledger-set current

cncli --version
cncli 5.3.2

Ubuntu 22.04

**Comment by mccamca** [comment]
No issues epoch 409 or 410.

**Comment by AndrewWestberg** [comment]
old issue. closing.
