### ISSUE TITLE
cncli-leaderlog-current.sh   (replace "tpraos" with "praos")

### ISSUE THREAD

**Issue by PILOT-Pool** [cardano-community/cncli#36]
Hi all! 

I recently updated my cncli leader log scripts to what are in v5.3.2.

Specifically:

1) cncli-leaderlog-current.sh
2) cncli-leaderlog-next.sh
3) cncli-leaderlog-prev.sh

When I ran the scripts the output was giving me block times that were not my pool's actual block times. 

I noticed in the scripts they use "tpraos" in the variables. So I changed my own scripts to say "praos". Then when I ran the scripts again they outputted correct block times for cncli-leaderlog-current.sh of which I verified against pooltool.io.

So maybe "tpraos" needs to be changed to "praos" in the above scripts, but I could be way off. Please let me know if I am off base on this. Thank you! 

And please keep up the great work with cncli!

**Comment by AndrewWestberg** [comment]
Fixed
