### ISSUE TITLE
Release supporting cardano-node v8

### ISSUE THREAD

**Issue by robinboening** [cardano-community/cncli#38]
Leaderlogs in [current release v5.3.2](https://github.com/cardano-community/cncli/releases/tag/v5.3.2) do not support cardano-node v8. I've seen a couple merged PRs (#33, #34) making it compatible with v8. I haven't been able to try these changes myself, but if it is confirmed working I am kindly asking for a new release 🙇‍♂️

Thank you!

**Comment by rphair** [comment]
@robinboening does your experience have anything in common with what we've reported in https://github.com/cardano-community/cncli/issues/25?

**Comment by robinboening** [comment]
@rphair I am currently using cncli v5.3.0 and since I updated my cardano node to v8.0.0 (now v8.1.1) cncli leaderlogs throw the following error

```
error: Invalid value for '--active-stake <active-stake>': invalid digit found in string
```

This seems to be fixed in the mentioned PRs, hence my request for a new release.

**Comment by rphair** [comment]
thanks @robinboening - that's different than what we were looking at 🙏

**Comment by rdlrt** [comment]
@robinboening 
> This seems to be fixed in the mentioned PRs, hence my request for a new release.

Mentioned PRs are fixes to the wrapper scripts , cncli binary (or it's version) would remain the same
