### ISSUE TITLE
Leaderlogs Incorrect

### ISSUE THREAD

**Issue by OYSTERPOOL** [cardano-community/cncli#44]
**Describe the bug**
Leaderlogs generated by CNCLI 1.5 days before epoch 465 are incorrect and do not match leaderlogs generated by CLI.
Around 0.5 days into the epoch I forced CNCLI to recalculate the leaderlogs and it produced the same leadership schedule as CLI.
I experienced a similar issue two epochs previously.

**To Reproduce**
Compare the leadership schedule generated by CNCLI with the leadership schedule generated by CLI 1.5 days before the epoch transition.

**Expected behavior**
Leaderlogs generated by CNCLI 1.5 days before the epoch change should match leaderlogs generated by running the 'cardano-cli query leadership-schedule'

As requested, active stake is 15,294,532 ₳ 

I will monitor this over the next few epochs and report if it happens again.

**Comment by AndrewWestberg** [comment]
If it happens again, please compress and attach your db as it is likely been corrupted and calculating the nonce incorrectly.  Are you syncing the db just before the time of running leaderlogs, or syncing continuously with a service?

**Comment by OYSTERPOOL** [comment]
Hi Andrew. I'm syncing the cncli db continuously, it's running as a systemd service. If the db was corrupt wouldn't it produce the same incorrect result when I force the recalculation of the leaderlogs?

I'll let you know what happens in an hour or so when the next leaderlogs are produced.

**Comment by OYSTERPOOL** [comment]
All good this epoch!

**Comment by AndrewWestberg** [comment]
Very strange. Do you happen to know the exact time you ran it when it calculated incorrectly? The only thing I can think of was it grabbed the wrong block for the nonce calculation.  This might happen if you try to run it exactly at 1.5 days until epoch time. Make sure to wait at least 20 minutes after that before running it.

**Comment by oximancer** [comment]
I have the same (stake pool BKV) in the last few epochs, cncli calculates the leaderlogs completely incorrectly (you can check starting from epoch 463 here https://pooltool.io/pool/28affa3c001052c65da45811a019f85df9bdc89c9a48cb24062f0c38/epochs ). 
<img width="599" alt="image" src="https://github.com/cardano-community/cncli/assets/142328686/2bba1a9b-3f9c-48e9-af4d-a4923deee4b4">

I checked/compared with standard cli, standard cli shows the leaderlogs properly ('cardano-cli query leadership-schedule...').
I was trying to fix it by completely deleting cncli db, but it resynced and showed again no proper result.
cncli calculated 8 blocks for me for this epoch (466) and currently saying that I have already missed 3 of them, while standard cli shows only 2 and in the future.
```
     SlotNo                          UTC Time
-------------------------------------------------------------
     116086022                   2024-02-11 11:51:53 UTC
     116319774                   2024-02-14 04:47:45 UTC
```

Please, help me fix the issue, I'm losing some delegators who are watching the stats on pooltool...
My cncli version `cncli v6.0.0 <5ab24a2> (x86_64-unknown-linux-gnu)`
My cardano-node version `cardano-node 8.7.3 - linux-x86_64 - ghc-8.10`

**Comment by AndrewWestberg** [comment]
Can you check to see whether the nonce is calculated correctly for the epoch?

**Comment by oximancer** [comment]
> Can you check to see whether the nonce is calculated correctly for the epoch?

Could you guide me or point to the docs how to do it?

**Comment by oximancer** [comment]
With cncli


```
bkvbp@cnode-bp:/opt/cardano/cnode$ cncli nonce --byron-genesis ./files/byron-genesis.json -
-shelley-genesis ./files/shelley-genesis.json --db ./guild-db/cncli/cncli.db
1ed47e36537ad7e0d3b9b30c5612bb058e99b0269b8dd4cadcaefbb9845dd5ae
```

**Comment by oximancer** [comment]
with cardano-cli
`cardano-cli query protocol-state --mainnet > prot.json`
File content:
```
bkvbp@cnode-bp:~$ head -n 20 prot.json
{
    "candidateNonce": {
        "contents": "646ef969ff7b676150cd2202f1c20852990191d8dc2d2a2f49a6379e802ce7fc",
        "tag": "Nonce"
    },
    "epochNonce": {
        "contents": "1ed47e36537ad7e0d3b9b30c5612bb058e99b0269b8dd4cadcaefbb9845dd5ae",
        "tag": "Nonce"
    },
    "evolvingNonce": {
        "contents": "646ef969ff7b676150cd2202f1c20852990191d8dc2d2a2f49a6379e802ce7fc",
        "tag": "Nonce"
    },
    "labNonce": {
        "contents": "e66edfec259ba117b5674275d36e0ddab695ad56eec5e09e0b707c1bde1c6523",
        "tag": "Nonce"
    },
    "lastEpochBlockNonce": {
        "contents": "b36684e1e3b5de9b143105db307db44b777549fe05718fe105dcece63bee0408",
        "tag": "Nonce"
```

**Comment by oximancer** [comment]
nonce looks the same for cardano-cli and cncli.

**Comment by AndrewWestberg** [comment]
If nonce is the same and results are different, you're passing a wrong option to cncli. Make sure you send praos and not tpraos.

**Comment by oximancer** [comment]
Checked cncli manually, the leaderlogs looked good. Looks like some guild scripts were broken, I upgraded them to alpha, started to sync from scratch and now the data is displayed correctly. Thank you for help!

**Comment by rayanebel** [comment]
@AndrewWestberg I've the same issue, according to your previous comment, in my case I have different value in nonce using `cncli` and `cardano-cli`. I'm using the latest version 6.0.1.

What can I do to find out what's going on?

```bash
cncli sync --host 127.0.0.1  --port 3001 --network-magic 1 --no-service
 2024-02-19T15:43:30.419Z INFO  cncli::nodeclient::sync > get_intersect_blocks took: 328.217µs
 2024-02-19T15:43:30.422Z INFO  cncli::nodeclient::sync > block 1949703 of 1949716:  99.99% sync'd
 2024-02-19T15:43:30.429Z INFO  cncli::nodeclient::sync > block 1949716 of 1949716: 100.00% sync'd
 2024-02-19T15:43:30.429Z INFO  cncli::nodeclient::sync > Exiting...
```

```bash
cncli nonce --shelley-genesis /config/shelley-genesis.json --byron-genesis /config/byron-genesis.json --db cncli.db
bfe8ff04bb6d4a3bccb165c2dd3987a1a9d37b8c881b2b38e1c8bde6a00745cc
```

```bash
cncli status --shelley-genesis /config/shelley-genesis.json --byron-genesis /config/byron-genesis.json --db cncli.db
{
 "status": "ok"
}
```

```bash
cardano-cli query protocol-state --testnet-magic 1 > prot.json
head -n 20 prot.json

{
    "candidateNonce": {
        "contents": "43e701c866d52882b04a18ec812cca7470d3e50a5082a378390b2c1a68002393",
        "tag": "Nonce"
    },
    "epochNonce": {
        "contents": "b6fb8f784745eddab46cebedfee1afb4cc548c9995e8f676e79162b4c8f05002",
        "tag": "Nonce"
    },
    "evolvingNonce": {
        "contents": "eeecb22cb760e241e8d8321a19c0a6b0cabb75cdde135fa6e40e26e344e719bb",
        "tag": "Nonce"
    },
    "labNonce": {
        "contents": "acf859440c91e2b0fbba7b2dcc10c3c01c83c163a9f8d8118335aa9ff30f9d7e",
        "tag": "Nonce"
    },
    "lastEpochBlockNonce": {
        "contents": "a63b4f1ba1408a92dad3933137a64495453c6f42d7eeb349eb8db10065d37ed4",
        "tag": "Nonce"
     }
}
```

If I directly request the leaderlogs on the nonce returned by the cardano-cli it works I have the same result between the output from `cncli` and the one from `cardano-cli`

```bash
cncli leaderlog --active-stake $ACTIVE_STAKE \
    --byron-genesis /config/byron-genesis.json \
    --pool-id xxxxxxxxxxxxxxxxxxx \
    --pool-stake $POOL_STAKE \
    --pool-vrf-skey /vault/secrets/vrf.skey \
    --shelley-genesis /config/shelley-genesis.json \
    --tz UTC \
    --nonce b6fb8f784745eddab46cebedfee1afb4cc548c9995e8f676e79162b4c8f05002
```

**Comment by AndrewWestberg** [comment]
@rayanebel Can you upload your cncli.db file somewhere? There's an issue with the sync and I'd need to see the db file to figure out where it went wrong. After you back it up, deleting the db and re-syncing should fix the issue temporarily.

**Comment by AndrewWestberg** [comment]
I believe these leaderlogs are incorrect due to running too close to the stability window. Do not run leaderlogs at exactly 1.5 days before epoch. Wait another 10 minutes and then run it.
