### ISSUE TITLE
[FEATURE REQUEST] Calculate Leader Logs for Any Previous Epoch

### ISSUE THREAD

**Issue by rayanebel** [cardano-community/cncli#51]
**Describe the solution you'd like**

Hi!

In the latest release of `cncli`, we can use the `--nonce` flag to provide the epoch nonce and avoid waiting for the database to sync. I wonder if it is possible to adapt the leader logs calculation logic to calculate the slot schedule for any epoch in the past ?

Currently, if I pass the nonce of an older epoch, for example: 485, and use the command `cncli leaderlog`, I always get the slot schedule for the current epoch.

This feature would be really helpful if we want to perform reporting and check the slots of an older epoch. Regarding the stake-snapshot, we can now use the `--active-stake` and `--pool-stake` flags and retrieve the corresponding values by using external APIs like **BlockFrost** or **Koios**.

Thanks!

**Comment by AndrewWestberg** [comment]
Seems like something that could be added.

**Comment by AndrewWestberg** [comment]
Closed by -> https://github.com/cardano-community/cncli/pull/52
Released in v6.2.0
