### ISSUE TITLE
Rust error on "cncli.sh ptsendtip"

### ISSUE THREAD

**Issue by asnakep** [cardano-community/cncli#53]
Hello Andrew,

I just installed new cncli v6.2.0 and after checking all cncli related systemd services (CNTools deployment), I noticed the following error on "cncli.sh ptsendtip"

thread '<unnamed>' panicked at /project/src/nodeclient/sync.rs:326:44:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I rolled back to v6.1.0 in order to have pooltool sendtip.

Thank you,
cheers,
Manuel

**Comment by asnakep** [comment]
Hello Andrew,

thanks for the quick fix, I've just upgraded to cncli v6.2.1 and pooltool sendtip works smoothly.

Cheers,
Manuel

**Comment by AndrewWestberg** [comment]
Fixed in v6.2.1 -> https://github.com/cardano-community/cncli/releases/tag/v6.2.1
