### ISSUE TITLE
[FEATURE REQUEST] Determine next epoch nonce without local DB

### ISSUE THREAD

**Issue by rayanebel** [cardano-community/cncli#55]
Hi!

I would like to know if its possible to update the `nonce` command to be able calculate the nonce of the next epoch without using the local DB. I'm currently using BlockFrost for an internal project but,  unfortunately its not possible to get the nonce of the next epoch in advance. 

Is it possible to improve something on your side ? If its not relevant for this project, I'd be happy if you could tell me what data I need to retrieve to make this calculation? 

Thanks @AndrewWestberg for the previous feature you've implemented it works :)

Thanks you!

**Comment by rdlrt** [comment]
You can find nonce for next epoch once available from https://api.koios.rest/#get-/epoch_info OR use CLI to capture protocol-state which will include next epoch's nonce

**Comment by rayanebel** [comment]
@rdlrt Thanks for your reply. As we are mainly using BlockFrost currently, we can't change or use another external services.I looked at the `cardano-cli query protocol-state` command. Which field corresponding to the next epoch nonce ? _(maybe not available yet we are not close to the end of the current epoch)_

```bash
 "candidateNonce": {
        "contents": "b491a560c8a76ac62050d5c1d31f486b5e9b0d102ed017133951e68ad13e6a2d",
        "tag": "Nonce"
    },
    "epochNonce": {
        "contents": "28f083638b1f54a162d87256d9aa7c6146be37cd972d9924c278ecc97d496adb",
        "tag": "Nonce"
    },
    "evolvingNonce": {
        "contents": "b491a560c8a76ac62050d5c1d31f486b5e9b0d102ed017133951e68ad13e6a2d",
        "tag": "Nonce"
    },
    "labNonce": {
        "contents": "5b45a3f2c168932d56b491a2caf735ed6d1c7c75b11f0f05bc5aae29548c3fd3",
        "tag": "Nonce"
    },
    "lastEpochBlockNonce": {
        "contents": "bc793a478f22193859c7a2b07c4ea5903982a0509e14efeb0c7b65bf630ce103",
        "tag": "Nonce"
    },
```

**Comment by rdlrt** [comment]
See reference [here](https://github.com/cardano-community/koios-artifacts/blob/main/files/grest/cron/jobs/populate-next-epoch-nonce.sh) for deriving nonce using that output
