### ISSUE TITLE
CNCLI Leaderlog and Validation Error Causing CNode Restarts

### ISSUE THREAD

**Issue by FreeYorkPool** [cardano-community/cncli#56]
Hi Andrew,

I have an issue with the CNCLI leaderlog and a validation error. My relay had CNCLI 6.2.1 and Node 8.9.3 installed. I installed CNCLI via GuildOps tools. My node, running as a systemd service, always restarts after encountering this issue.

**Logs:**
Here are the logs from journalctl -xe -u cnode*:
![photo_2024-06-09 08 40 45](https://github.com/cardano-community/cncli/assets/75595276/7d4a117e-b39c-4449-86b8-3589464cc565)

**Comment by AndrewWestberg** [comment]
@FreeYorkPool How much ram is on the server running things?  I feel like the node is crashing causing the cncli error, not the other way around.

**Comment by FreeYorkPool** [comment]
I'm running on Contabo with 24GB of RAM. Until now, RAM usage with CNCLI installed has been around 12GB on this relay. The BP and another relay are still running on Node 8.7.3 without CNCLI and are running well without crashes.

**Comment by AndrewWestberg** [comment]
@FreeYorkPool How much Swap space on this instance?

**Comment by AndrewWestberg** [comment]
Can you monitor ram usage while cncli is running?

**Comment by FreeYorkPool** [comment]
The problem is solved. I migrated to another server, and it works well. Thank you for your help.
