### ISSUE TITLE
Leaderlog not being run for next epoch

### ISSUE THREAD

**Issue by whankinsiv** [cardano-community/cncli#57]
**Describe the bug**
Attempting ./cncli.sh leaderlog within 1.5 days before next epoch but script not checking leaderlog for next epoch. 

**To Reproduce**
1. Go to directory where cncli.sh is located
2. Sync node with ./cncli.sh sync
3. Execute ./cncli.sh leaderlog
4. See that leaderlog does not run for following epoch

**Expected behavior**
Leaderlog for epoch 190 to say "Leaderlogs already calculated for epoch 490, skipping!" and then script to calculate leaderlog for epoch 491 and add new blocks to database. 

**Screenshots**
<img width="565" alt="Screenshot 2024-06-12 at 1 41 40 PM" src="https://github.com/cardano-community/cncli/assets/75007804/e18c14bf-2c0f-4f2f-ad42-7951a0677cb1">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS 
 - Cardano Node Version 8.9.0

**Comment by rdlrt** [comment]
leaderlog calculation from cncli.sh has been delayed to 8/10th of an epoch as there have been reports of invalid nonce at first block post 7/10th of an epoch (the expected time when this should be available) - invalid nonce was only seen on some nodes, thus - an edge case not easily replicable.

Also, once in conway era, we should be able to revert back as nonce would be finalized at the correct stability window (6/10th of an epoch)

**Comment by whankinsiv** [comment]
> leaderlog calculation from cncli.sh has been delayed to 8/10th of an epoch as there have been reports of invalid nonce at first block post 7/10th of an epoch (the expected time when this should be available) - invalid nonce was only seen on some nodes, thus - an edge case not easily replicable.
> 
> Also, once in conway era, we should be able to revert back as nonce would be finalized at the correct stability window (6/10th of an epoch)

Good to know. Thank you.
