### ISSUE TITLE
Incorrect leader schedule

### ISSUE THREAD

**Issue by QCPOLstakepool** [cardano-community/cncli#63]
cncli gave a result of 1 block for QCPOL for epoch 509 (ran in epoch 508), but when I checked the cardano-node log after the block wasn't minted it said pool was not leader. I tried to run the leadership-schedule with cardano-cli for epoch 509 (using --current) and it outputs 0 block. I tried using cncli for epoch 509 while in epoch 509 (using --current) and it still outputs the same 1 block.

using cncli 6.3.0, same setup since forever. haven't changed a thing. never had problems
before (been using cncli for over 2 years).

**Comment by rphair** [comment]
Have you added the option `--consensus cpraos` since the hard fork?
https://github.com/cardano-community/cncli/blob/develop/USAGE.md#show-leaderlog-help

**Comment by QCPOLstakepool** [comment]
I have not, will try again with it ! Thanks.

**Comment by QCPOLstakepool** [comment]
It's working!
